name: esd-project

networks:
  esd-net:
    driver: bridge

services:
  listing-service:
    build:
      context: .
      dockerfile: ./listing-service/Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - esd-net

  reservation-service:
    build:
      context: .
      dockerfile: ./reservation-service/Dockerfile
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - OUTSYSTEMS_NOTIFY_URL=https://personal-42atob5v.outsystemscloud.com/Notification/rest/NotificationAPI/notify
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  striking-svc:
    build:
      context: .
      dockerfile: ./striking-svc/Dockerfile
    ports:
      - "8013:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - esd-net

  strike-service:
    build:
      context: .
      dockerfile: ./strike-service/Dockerfile
    ports:
      - "8003:8000"
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - CLAIMANT_SERVICE_URL=http://claimant-service:5000
      - STRIKING_SVC_URL=http://striking-svc:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
      claimant-service:
        condition: service_started
      striking-svc:
        condition: service_started
    networks:
      - esd-net

  notification-service:
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    ports:
      - "8004:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - OUTSYSTEMS_NOTIFY_URL=https://personal-42atob5v.outsystemscloud.com/Notification/rest/Notification/Notify
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  registration-service:
    build:
      context: .
      dockerfile: ./registration-service/Dockerfile
    ports:
      - "8006:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_USERNAME=SFRB_Notif_BOt
      - CLAIMANT_SERVICE_URL=http://claimant-service:5000
      - VENDOR_SERVICE_URL=http://vendor-service:5000
    depends_on:
      claimant-service:
        condition: service_started
      vendor-service:
        condition: service_started
    networks:
      - esd-net

  expiry-monitor-service:
    build:
      context: .
      dockerfile: ./expiry-monitor-service/Dockerfile
    ports:
      - "8005:5000"
    environment:
      - LISTING_SERVICE_URL=http://listing-service:8000
      - CRON_INTERVAL_MINUTES=1
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      listing-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  handle-cancellation-service:
    build:
      context: .
      dockerfile: ./handle-cancellation-service/Dockerfile
    ports:
      - "8007:5000"
    environment:
      - RESERVATION_SERVICE_URL=http://reservation-service:8000
      - LISTING_SERVICE_URL=http://listing-service:8000
      - STRIKE_SERVICE_URL=http://strike-service:8000
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    user: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - esd-net

  collection-service:
    build:
      context: .
      dockerfile: ./collection-service/Dockerfile
    ports:
      - "8009:5000"
    environment:
      - RESERVATION_SERVICE_URL=http://reservation-service:8000
      - LISTING_SERVICE_URL=http://listing-service:8000
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  claimant-service:
    build:
      context: .
      dockerfile: ./claimant-service/Dockerfile
    ports:
      - "8012:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - esd-net

  vendor-service:
    build:
      context: .
      dockerfile: ./vendor-service/Dockerfile
    ports:
      - "8011:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - esd-net

  collection-monitoring-service:
    build:
      context: .
      dockerfile: ./collection-monitoring-service/Dockerfile
    ports:
      - "8010:5000"
    environment:
      - RESERVATION_SERVICE_URL=http://reservation-service:8000
      - LISTING_SERVICE_URL=http://listing-service:8000
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672
      - CRON_INTERVAL_MINUTES=1
    depends_on:
      reservation-service:
        condition: service_started
      listing-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net

  reserve-composite-service:
    build: ./reserve-composite-service
    ports:
      - "8008:8000"
    depends_on:
      - listing-service
      - reservation-service
      - strike-service
      - notification-service
    networks:
      - esd-net

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    volumes:
      - ./kong.yml:/kong/kong.yml
    ports:
      - "9000:8000"
      - "9001:8001"
    networks:
      - esd-net

volumes:
  rabbitmq_data:
  postgres_data:

